"""Add net_worth_history table

Revision ID: 06344ed02138
Revises: 
Create Date: 2025-08-07 10:42:45.323961

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06344ed02138'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('net_worth_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_net_worth_history_date'), 'net_worth_history', ['date'], unique=True)
    op.create_index(op.f('ix_net_worth_history_id'), 'net_worth_history', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_net_worth_history_id'), table_name='net_worth_history')
    op.drop_index(op.f('ix_net_worth_history_date'), table_name='net_worth_history')
    op.drop_table('net_worth_history')
    # ### end Alembic commands ###
